import { Modules } from '../enums/module';
import { ModuleIdV2 } from '../enums/modules-idV2';
import { ModulesCatalog } from '../models';
// ModulesId.CAT_AREA_RES

const aux = [
    {
        name: 'Regiones',
        id: ModuleIdV2.CAT_REGIONES,
        url: 'catalogo/regiones',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_REGIONES,
    },
    {
        name: 'Instituciones',
        id: ModuleIdV2.CAT_INSTITUCIONES,
        url: 'catalogo/instituciones',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_INSTITUCIONES,
    },
    {
        name: 'Perfiles',
        id: ModuleIdV2.CAT_PERFILES,
        url: 'catalogo/perfiles',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_PERFILES,
    },
    {
        name: 'Nivel modalidad',
        id: ModuleIdV2.CAT_NIVEL_MOD,
        url: 'catalogo/nivel-modalidad',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_NIVEL_MOD,
    },
    {
        name: 'Usuario',
        id: ModuleIdV2.CAT_USUARIO_SIAC,
        url: 'catalogo/usuarios',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_USUARIO_SIAC,
    },
    {
        name: 'Periodo de Evaluación',
        id: ModuleIdV2.CAT_PERIOD_EVAL,
        url: 'catalogo/periodo-evaluacion',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_PERIOD_EVAL,
    },
    {
        name: 'Campus',
        id: ModuleIdV2.CAT_CAMPUS,
        url: 'catalogo/campus',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_CAMPUS,
    },
    {
        name: 'Áreas responsables',
        id: ModuleIdV2.CAT_AREAS_RESPONSABLE,
        url: 'catalogo/areas-responsabilidad',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_AREAS_RESPONSABLE,
    },
    {
        name: 'Áreas coporativas',
        id: ModuleIdV2.CAT_AREAS_CORP,
        url: 'catalogo/areas-corporativas',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_AREAS_CORP,
    },
    {
        name: 'Componentes',
        id: ModuleIdV2.CAT_COMPONENTE,
        url: 'catalogo/componentes',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_COMPONENTE,
    },
    {
        name: 'Ponderaciones',
        id: ModuleIdV2.CAT_PODERACION,
        url: 'catalogo/ponderaciones',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_PODERACION,
    },
    {
        name: 'Matriz UVM',
        id: ModuleIdV2.CAT_MATRIZ_UVM,
        url: 'catalogo/matriz-uvm',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_MATRIZ_UVM,
    },
    {
        name: 'Componente UVM',
        id: ModuleIdV2.CAT_COMPONENT_UVM,
        url: 'catalogo/matriz-uvm/componentes-uvm',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_MATRIZ_UVM,
    },
    {
        name: 'Indicador UVM',
        id: ModuleIdV2.CAT_INDICADOR_UVM,
        url: 'catalogo/matriz-uvm/indicador-uvm',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_MATRIZ_UVM,
    },
    {
        name: 'SubIndicador UVM',
        id: ModuleIdV2.CAT_SUBINDICADOR_UVM,
        url: 'catalogo/matriz-uvm/subindicador-uvm',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_MATRIZ_UVM,
    },
    {
        name: 'Normativa',
        id: ModuleIdV2.CAT_NORMATIVA,
        url: 'catalogo/normativas',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_NORMATIVA,
    },
    {
        name: 'Sedes',
        id: ModuleIdV2.CAT_SEDES,
        url: 'catalogo/sedes',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_SEDES,
    },
    {
        name: 'Instituciones acreditadoras',
        id: ModuleIdV2.CAT_INSTI_ACRED,
        url: 'catalogo/acreditadores',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_INSTI_ACRED,
    },
    {
        name: 'Criterios',
        id: ModuleIdV2.CAT_CRITERIO,
        url: 'catalogo/criterios',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_CRITERIO,
    },
    {
        name: 'Capítulos',
        id: ModuleIdV2.CAT_CAPITULO,
        url: 'catalogo/capitulos',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_CAPITULO,
    },
    {
        name: 'Elemento de evaluación',
        id: ModuleIdV2.CAT_ELEM_EVAL,
        url: 'catalogo/catalogo-elemento-evaluacion',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_ELEM_EVAL,
    },
    {
        name: 'Indicadores SIAC',
        id: ModuleIdV2.CAT_INDICADOR_SIAC,
        url: 'catalogo/indicadores-siac',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_INDICADOR_SIAC,
    },
    {
        name: 'Dependencia de área',
        id: ModuleIdV2.CAT_DEPENDENCIA_AREA,
        url: 'catalogo/dependencia-area',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_DEPENDENCIA_AREA,
    },
    {
        name: 'Subareas corporativas',
        id: ModuleIdV2.CAT_SUBAREAS_CORP,
        url: 'catalogo/subareas-corporativas',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_SUBAREAS_CORP,
    },
    {
        name: 'Evidencias',
        id: ModuleIdV2.CAT_EVIDENCE,
        url: 'catalogo/evidencias',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_EVIDENCE,
    },
    {
        name: 'Elemento de Evaluación',
        id: ModuleIdV2.CFG_ELEM_EVAL,
        url: 'configuracion/elemento-evaluacion',
        global: false,
        section: 'configuracion',
        key: Modules.CFG_ELEM_EVAL,
    },
    {
        name: 'Indicadores SIAC',
        id: ModuleIdV2.CFG_INDICADORES_SIAC,
        url: 'configuracion/indicadores-siac',
        global: false,
        section: 'configuracion',
        key: Modules.CFG_INDICADORES_SIAC,
    },
    {
        name: 'Escala de Medición',
        id: ModuleIdV2.CFG_ESCALA_MEDICION,
        url: 'configuracion/escala-medicion',
        global: false,
        section: 'configuracion',
        key: Modules.CFG_ESCALA_MEDICION,
    },
    {
        name: 'Configuración Bienvenida',
        id: ModuleIdV2.CFG_WELCOME,
        url: 'welcome-settings',
        global: false,
        section: 'welcome-settings',
        key: Modules.CFG_WELCOME,
    },
    {
        name: 'Captura de Metas y Resultados',
        id: ModuleIdV2.CAP_MET_RES,
        url: 'metas-resultados',
        global: false,
        section: 'metas-resultados',
        key: Modules.CAP_MET_RES,
    },
];

export const MODULESCATALOGV2 = aux.map((item) => new ModulesCatalog().deserialize(item));
