import { ModuleId } from '../enums';
import { Modules } from '../enums/module';
import { ModulesCatalog } from '../models';
// ModulesId.CAT_AREA_RES

const aux = [
    // {
    //     name: 'Áreas de responsabilidad',
    //     id: 1,
    //     url: 'catalogo/areas-responsabilidad',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_AREA_RES,
    // },
    // {
    //     name: 'Campus',
    //     id: 2,
    //     url: 'catalogo/campus',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_CAMPUS,
    // },
    // {
    //     name: 'Capítulos',
    //     id: 3,
    //     url: 'catalogo/capitulos',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_CAPITULO,
    // },
    // {
    //     name: 'Carreras',
    //     id: 4,
    //     url: 'catalogo/carreras',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_CARRERA,
    // },
    // {
    //     name: 'Criterios',
    //     id: 5,
    //     url: 'catalogo/criterios',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_CRITERIO,
    // },
    // {
    //     name: 'Instituciones acreditadoras',
    //     id: 6,
    //     url: 'catalogo/acreditadores',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_INSTI_ACRED,
    // },
    // {
    //     name: 'Instituciones acreditadoras procesos',
    //     id: 25,
    //     url: 'catalogo/acreditadores',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_INSTI_ACRED_PROC,
    // },
    // {
    //     name: 'Niveles de atención',
    //     id: 7,
    //     url: 'catalogo/nivel-de-atencion',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_NIV_ATEN,
    // },
    // {
    //     name: 'Niveles organizacionales',
    //     id: 8,
    //     url: 'catalogo/nivel-organizacional',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_NIV_ORGA,
    // },
    // {
    //     name: 'Regiones',
    //     id: 9,
    //     url: 'catalogo/regiones',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_REGIONES,
    // },
    // {
    //     name: 'Roles',
    //     id: 10,
    //     url: 'catalogo/roles',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_ROLES,
    // },
    // {
    //     name: 'Sedes',
    //     id: 11,
    //     url: 'catalogo/sedes',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_SEDES,
    // },
    // {
    //     name: 'Subáreas',
    //     id: 12,
    //     url: 'catalogo/subareas',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_SUB_AREA,
    // },
    // {
    //     name: 'Tipos de evidencia',
    //     id: 13,
    //     url: 'catalogo/tipos-evidencia',
    //     global: false,
    //     section: 'catalogo',
    //     key: Modules.CAT_TIPO_EVI,
    // },
    // {
    //     name: 'Asignación de roles',
    //     id: 22,
    //     url: 'configuracion/asignacion-roles',
    //     global: false,
    //     section: 'configuracion',
    //     key: Modules.CONF_ASIGN_ROL,
    // },
    // {
    //     name: 'Carga de archivos',
    //     id: 15,
    //     url: 'configuracion/carga-archivos',
    //     global: false,
    //     section: 'configuracion',
    //     key: Modules.CONF_CARG_ARCH,
    // },
    // {
    //     name: 'Índice de evidencias',
    //     id: 16,
    //     url: 'configuracion/indice-evidencias',
    //     global: false,
    //     section: 'configuracion',
    //     key: Modules.CONF_IND_EVI,
    // },
    // {
    //     name: 'Usuarios',
    //     id: 17,
    //     url: 'configuracion/usuarios',
    //     global: false,
    //     section: 'configuracion',
    //     key: Modules.CONF_USUARIO,
    // },
    // {
    //     name: 'Libro electrónico',
    //     id: 18,
    //     url: 'operacion/libro-electronico',
    //     global: false,
    //     section: 'operacion',
    //     key: Modules.OPE_LIB_ELEC,
    // },
    // {
    //     name: 'Registro evidencia - Carga',
    //     id: 27,
    //     url: 'operacion/registro-evidencias',
    //     global: false,
    //     section: 'operacion',
    //     key: Modules.OPE_REG_EVID_LOAD,
    // },
    // {
    //     name: 'Registro evidencia - Validación',
    //     id: 19,
    //     url: 'operacion/registro-evidencias',
    //     global: false,
    //     section: 'operacion',
    //     key: Modules.OPE_REG_EVID_VALID,
    // },
    // {
    //     name: 'Seguimiento a evaluación',
    //     id: 20,
    //     url: 'operacion/seguimiento-evaluacion',
    //     global: false,
    //     section: 'operacion',
    //     key: Modules.OPE_SEG_EVAL,
    // },
    // {
    //     name: 'Reportes',
    //     id: 26,
    //     url: 'reportes',
    //     global: false,
    //     key: Modules.REPORTES,
    // },
    // {
    //     name: 'Perfil',
    //     id: 30,
    //     url: 'mi-perfil',
    //     global: true,
    //     key: Modules.PERFIL,
    // },
    // {
    //     name: 'Vista de libro electrónico',
    //     id: 23,
    //     url: 'operacion/vista-libro-electronico',
    //     global: false,
    //     section: 'operacion',
    //     key: Modules.OPE_VISTA_PREVI,
    // },
    // {
    //     name: 'Vista de libro electrónico / seccion',
    //     id: 24,
    //     url: 'operacion/vista-libro-electronico/seccion',
    //     global: false,
    //     section: 'operacion',
    //     key: Modules.OPE_VISTA_PREVI_SEC,
    // },
    //TODO SIAC
    {
        name: 'Perfiles',
        id: ModuleId.CAT_PERFILES,
        url: 'catalogo/perfiles',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_PERFILES,
    },
    {
        name: 'Nivel modalidad',
        id: ModuleId.CAT_NIVEL_MOD,
        url: 'catalogo/nivel-modaliad',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_NIVEL_MOD,
    },
    {
        name: 'Usuario',
        id: ModuleId.CAT_USUARIO_SIAC,
        url: 'configuracion/usuarios',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_USUARIO_SIAC,
    },
    {
        name: 'Periodo de Evaluación',
        id: ModuleId.CAT_PERIOD_EVAL,
        url: 'configuracion/periodo-evaluacion',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_PERIOD_EVAL,
    },
    {
        name: 'Áreas responsables',
        id: ModuleId.CAT_AREAS_RESPONSABLE,
        url: 'catalogo/areas-responsabilidad',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_AREAS_RESPONSABLE,
    },
    {
        name: 'Áreas coporativas',
        id: ModuleId.CAT_AREAS_CORP,
        url: 'catalogo/areas-corporativas',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_AREAS_CORP,
    },
    {
        name: 'Componentes',
        id: ModuleId.CAT_COMPONENTE,
        url: 'catalogo/componentes',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_COMPONENTE,
    },
    {
        name: 'Ponderaciones',
        id: ModuleId.CAT_PODERACION,
        url: 'catalogo/ponderaciones',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_PODERACION,
    },
    {
        name: 'Matriz UVM',
        id: ModuleId.CAT_MATRIZ_UVM,
        url: 'catalogo/matriz-uvm',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_MATRIZ_UVM,
    },
    {
        name: 'Normativa',
        id: ModuleId.CAT_NORMATIVA,
        url: 'catalogo/normativa',
        global: false,
        section: 'catalogo',
        key: Modules.CAT_NORMATIVA,
    },
    {
        name: 'Configuración general',
        id: ModuleId.CONF_NIV_AREA_RESPONSABLE,
        url: 'configuracion/configuracion-general',
        global: false,
        section: 'configuracion',
        key: Modules.CONF_NIV_AREA_RESPONSABLE,
    },
    {
        name: 'Elemento de evaluación',
        id: ModuleId.CONF_ELEM_EVAL,
        url: 'configuracion/elemento-evaluacion',
        global: false,
        section: 'configuracion',
        key: Modules.CONF_ELEM_EVAL,
    },
    {
        name: 'Indicadores',
        id: ModuleId.CONF_INDICADORES,
        url: 'configuracion/elemento-evaluacion',
        global: false,
        section: 'configuracion',
        key: Modules.CONF_INDICADORES,
    },
    {
        name: 'Escala de medición',
        id: ModuleId.CONF_ESCALA_MEDICION,
        url: 'configuracion/escala-medición',
        global: false,
        section: 'configuracion',
        key: Modules.CONF_ESCALA_MEDICION,
    },
    {
        name: 'Proceso de copiado',
        id: ModuleId.CONF_PROC_COPIADO,
        url: 'configuracion/proceso-copiado',
        global: false,
        section: 'configuracion',
        key: Modules.CONF_PROC_COPIADO,
    },
    {
        name: 'Captura de metas y resultados',
        id: ModuleId.CONF_PROC_COPIADO,
        url: 'metas-resultados',
        global: false,
        section: '',
        key: Modules.CAP_MET_RES,
    },
    {
        name: 'Carga de evidencias',
        id: ModuleId.CARGA_EVIDENC_SIAC,
        url: 'metas-resultados',
        global: false,
        section: '',
        key: Modules.CARGA_EVIDENC_SIAC,
    },
    {
        name: 'Ejecucióm de autoevaluación',
        id: ModuleId.EJEC_AUTO_EVAL,
        url: 'ejecucion-autoevaluacion',
        global: false,
        section: '',
        key: Modules.EJEC_AUTO_EVAL,
    },
    {
        name: 'Revisiom de autoevaluación',
        id: ModuleId.REV_AUTO_EVAL,
        url: 'revision-autoevaluacion',
        global: false,
        section: '',
        key: Modules.REV_AUTO_EVAL,
    },
    {
        name: 'Plan de mejora',
        id: ModuleId.PLAN_MEJORA,
        url: 'plan-mejora',
        global: false,
        section: '',
        key: Modules.PLAN_MEJORA,
    },
    {
        name: 'Auditoria',
        id: ModuleId.AUDITORIA,
        url: 'auditoria',
        global: false,
        section: '',
        key: Modules.AUDITORIA,
    },
    {
        name: 'Reportes y seguimiento',
        id: ModuleId.REP_SEGUI_SIAC,
        url: 'reporte-seguimiento',
        global: false,
        section: '',
        key: Modules.REP_SEGUI_SIAC,
    },
    {
        name: 'Carga de formatos',
        id: ModuleId.CONF_FORM_UPLOAD,
        url: 'configuracion/carga-de-formatos',
        global: false,
        section: '',
        key: Modules.CONF_FORM_UPLOAD,
    },
];

export const MODULESCATALOG = aux.map((item) => new ModulesCatalog().deserialize(item));
